apiVersion: backup.cnd.dk/v1
kind: Backup
metadata:
  name: backup-sample
  namespace: default
spec:
  source:
    namespace: "default"
    labelSelector:
      matchLabels:
        app: "my-app"
  schedule: "*/1 * * * *"  # Every 1 minute for testing
  storageLocation:
    provider: "minio"
    bucket: "test-backups"
    endpoint: "http://localhost:9000"
    username: "minioadmin"
    password: "minioadmin"
    
