apiVersion: backup.cnd.dk/v1
kind: Backup
metadata:
  labels:
    app.kubernetes.io/name: cluster-backup-operator
    app.kubernetes.io/managed-by: kustomize
  name: backup-sample
spec:
  source:
    namespace: "default"
    labelSelector:
      matchLabels:
        app: "nginx"
  schedule: "0 2 * * *"  # Daily at 2 AM
  retention: "30d"       # Keep for 30 days
  storageLocation:
    provider: "minio"
    bucket: "backups"
    endpoint: "http://minio:9000"
    credentialsSecret: "minio-credentials"
