apiVersion: backup.cnd.dk/v1
kind: Backup
metadata:
  name: test-namespace-backup
  namespace: default
spec:
  source:
    namespace: "test-backup"
    resourceTypes: ["deployments", "services", "configmaps", "secrets"]
    labelSelector:
      matchLabels:
        backup: "enabled"
  schedule: "*/5 * * * *"  # Every 5 minutes for testing
  retention: "7d"
  storageLocation:
    provider: "minio"
    bucket: "k8s-backups"
    endpoint: "http://172.17.0.3:9000"  # Update with actual Minio container IP
    accessKey: "minioadmin"
    secretKey: "minioadmin123"